[package]
name = "bounce_matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"
embedded-hal = "0.2.5"
rp-pico = "0.3.0"
rp2040-hal = "0.4.0"
panic-halt = "0.2.0"
embedded-time = "0.12.1"
rp2040-boot2 = "0.2.0"
